### ISSUE TITLE
[Feature Request] Input obsolete or non-standard IPA symbols

### ISSUE THREAD

**Issue by mkpoli** [Vince14Genius/IPA-Keyboard-iOS#1]
Thank you for providing such a cool tool. It's so useful.

Sometimes I need to type some special characters like ɿ, ʅ, ʮ, ʯ, ᴀ, ᴇ. I hope this App can type this as well, or at least provide an option to enable those characters.

There is a pretty good list here on Wikipedia.
https://en.wikipedia.org/wiki/Obsolete_and_nonstandard_symbols_in_the_International_Phonetic_Alphabet

**Comment by Vince14Genius** [comment]
Thank you for your feedback!

Actually I was already planning to add this feature for the next release. It's just that I was very busy with school work, college applications, and other things over the past few months; when I get spare time, I will work on it. 

As of now, the full list of features that will be added in future releases are as follows:

- IPA Extended (extIPA)
- Obsolete symbols
- Nonstandard symbols
- Custom keyboard (custom keys and custom order)
- (maybe) Recently used keys
- Press and hold on backspace/delete button to rapidly delete
- Link to the Wikipedia IPA page in app
- Link to Bug Report / Feedback in app

**Comment by mkpoli** [comment]
Thank you for your reply and again for your great app. I'm looking forward to the next update. Keep up and have a nice day. 😄

**Comment by mkpoli** [comment]
I suggest to add some of the following symbols. 😄

## 塞擦音符號
清雙脣塞擦音 p͡ɸ
濁雙脣塞擦音 b͡β
清雙脣脣齒塞擦音 p͡f
濁雙脣脣齒塞擦音 b͡v
清脣齒塞擦音 p̪͡f
濁脣齒塞擦音 b̪͡v
清齒無噝塞擦音 t̪͡θ
濁齒無噝塞擦音 d̪͡ð
清齒有噝塞擦音 t̪͡s̪
濁齒有噝塞擦音 d̪͡z̪
清齒齦塞擦音 t͡s
濁齒齦塞擦音 d͡z
清齶齦塞擦音 t̠͡ʃ t͡ʃ
濁齶齦塞擦音 d̠͡ʒ d͡ʒ
清齒齦邊塞擦音 t͡ɬ
濁齒齦邊塞擦音 d͡ɮ
清齦齶塞擦音 ȶ͡ɕ t͡ɕ
濁齦齶塞擦音 ȡ͡ʑ d͡ʑ
清翹舌塞擦音 ṭ͡ṣ t͡ṣ
濁翹舌塞擦音 ḍ͡ẓ d͡ẓ
清捲舌塞擦音 ʈ͡ʂ t͡ʂ
濁捲舌塞擦音 ɖ͡ʐ d͡ʐ
清硬齶塞擦音 c͡ç
濁硬齶塞擦音 ɟ͡ʝ
清軟齶塞擦音 k͡x
濁軟齶塞擦音 g͡ɣ
清小舌塞擦音 q͡χ
濁小舌塞擦音 ɢ͡ʁ
清咽塞擦音 ʡ͡ħ
濁咽塞擦音 ʡ͡ʕ
清喉塞擦音 ʔ͡h

## 塞擦音合字
清齒齦塞擦音 ʦ
濁齒齦塞擦音 ʣ
清齶齦塞擦音 ʧ
濁齶齦塞擦音 ʤ
清齦齶塞擦音 ʨ
濁齦齶塞擦音 ʥ

## 邊化擦音
清齒齦邊化擦音 ʪ
濁齒齦邊化擦音 ʫ

## 齦齶音符號
清齦齶塞音 ȶ
濁齶齦塞音 ȡ
齶齦鼻音 ȵ
齶齦邊近音 ȴ

## 翹舌音符號
翹舌 ◌̣
清翹舌擦音 ṣ
濁翹舌擦音 ẓ

## 齶咽音
齶咽摩擦 ◌͌
齶咽擦音 ʩ

## 送氣符號
送氣 ◌ʻ

## 舌尖元音符號
舌尖前不圓脣元音 ɿ
舌尖前圓脣元音 ʮ
舌尖後（捲舌）不圓脣元音 ʅ
舌尖後（捲舌）圓脣元音 ʯ

## 中元音央元音符號
開央不圓脣元音 ᴀ
中前不圓脣元音 ᴇ

## 調類符號
陰平 ꜀◌
陽平 ꜁◌
陰上 ꜂◌
陽上 ꜃◌
陰去 ◌꜄
陽去 ◌꜅
陰入 ◌꜆
陽入 ◌꜇
輕聲 ꞏ◌

**Comment by Vince14Genius** [comment]
lol I procrastinate so much
thanks for the suggestions
I'll get to work asap

**Comment by noraworld** [comment]
@Vince14Genius I want the `/ʤ/` symbol, not `/dʒ/`. Over three years have passed since this issue was opened, but I would be appreciate if you could implement this.

I really love this app, it’s super useful. Thank you!
