### ISSUE TITLE
Version 1.0.1 issues

### ISSUE THREAD

**Issue by kokoshneta** [Vince14Genius/IPA-Keyboard-iOS#3]
I’ve been using this excellent keyboard for several years and saw the new layout yesterday (it auto-updated at some point). Overall very welcome changes – lots of improvements.

There are two things I’ve identified that detract, however:

1. Under “Current bugs”, I see this:

> The bottom of "◌̩" is cut off (this is probably a font problem)

So far, though, the syllabicity bar appears to have disappeared completely from the keyboard. I’m sure it was there in the previous version, but I can’t find it anywhere now. Have I gone blind, or was it left out due to the bug?

2. Unfortunately, after using the new layout for about a minute, it completely froze on me, and I haven’t been able to unfreeze it since – whenever I switch to the IPA keyboard, the entire keyboard is just non-responsive. Horizontal scrolling through keys doesn’t work, and no input is registered. The ABC key doesn’t work either, though the globe button underneath does still work, enabling me to switch back to a functional keyboard.

The first time the freezing occurred, it actually froze the entire phone completely – couldn’t even turn off the screen. Holding down the power button for a while jiggled something and it eventually did what looked like a soft-boot, but nothing else worked. This hasn’t happened since.

This is all on an iPhone XS running iOS 13.4.1.

**Comment by Vince14Genius** [comment]
Sorry for the late response.

1. Fixed in the newest beta version; the public version will be available soon. 
    - Meanwhile in version 1.0.1, you can find the syllabicity bar (◌̩) as the key that has a dot instead of a line below the dotted circle; this key is also conveniently located next to its corresponding upper version <◌̍> .

2. I was never able to reproduce this problem. Has it ever happened to you again?
